VERSION: 0.2.0
CONFIGURATION: Debug
NUGETPACKAGES:
  - Core:
    Name: Thark.Core
    Version: 0.2.0
    Location: src/Thuria.Thark.Core
    IsBeta: true
    Frameworks:
      - net461
      - net472
      - net48
      - netstandard2.0
      - netcoreapp3.0
  - StatementBuilder:
    Name: Thark.StatementBuilder
    Version: 0.2.0
    Location: src/Thuria.Thark.StatementBuilder
    IsBeta: true
    Frameworks:
      - net461
      - net472
      - net48
      - netstandard2.0
      - netcoreapp3.0
  - DataAccess:
    Name: Thark.DataAccess
    Version: 0.2.0
    Location: src/Thuria.Thark.DataAccess
    IsBeta: true
    Frameworks:
      - net461
      - net472
      - net48
      - netstandard2.0
      - netcoreapp3.0
  - DataAccessSqlServer:
    Name: Thark.DataAccess.SqlServer
    Version: 0.2.0
    Location: src/Thuria.Thark.DataAccess.SqlServer
    IsBeta: true
    Frameworks:
      - net461
      - net472
      - net48
      - netstandard2.0
      - netcoreapp3.0
  - DataAccessSqlite:
    Name: Thark.DataAccess.Sqlite
    Version: 0.2.0
    Location: src/Thuria.Thark.DataAccess.Sqlite
    IsBeta: true
    Frameworks:
      - net461
      - net472
      - net48
      - netstandard2.0
      - netcoreapp3.0
  - DataModel:
    Name: Thark.DataModel
    Version: 0.2.0
    Location: src/Thuria.Thark.DataModel
    IsBeta: true
    Frameworks:
      - net461
      - net472
      - net48
      - netstandard2.0
      - netcoreapp3.0
